### ISSUE TITLE
Can it run on Windows 10

### ISSUE THREAD

**Issue by Ak-k** [nrajasin/Network-intrusion-dataset-creator#5]
I removed sudo and mentioned Ethernet interface in tshark to make it work on windows 10.I am getting Json decode error and sometime it stuck at capturing Ethernet.Did someone try to run this program in windows 10?

**Comment by montysinha7** [comment]
Wondering if anyone was able to get this working I am having issues with installing the requirements failing to install apt-clone and also Brlapi

**Comment by Ak-k** [comment]
> Wondering if anyone was able to get this working I am having issues with installing the requirements failing to install apt-clone and also Brlapi

I was able to run it successfully on Linux.No need to run apt-clone,just install only required libraries.

**Comment by Ak-k** [comment]
I was able to run it by installing tshark v2.6.15. Now it run perfectly on both windows 10 and ubuntu.

**Comment by larbiaryeh** [comment]
@Ak-k can you please help me get this code running in windows. I have anaconda installed abs in using jupyterlab to run this in windows 10. Please help me. A step by step will be very much appreciated. Thank you
